apiVersion: v1
kind: Service
metadata:
  name: japan-service
  namespace: ostad
spec:
  type: LoadBalancer
  selector:
    app: japan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # nodePort: 30000