name: Module 7 Assignment - Japan (CI using GHA)

on:
  push:
    branches:
      - assignment/japan

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run next lint
        run: npx next lint
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define Image Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: farhansabbir/next-japan
          tags: |
            type=raw,value=latest


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
