name: View contents of hello.txt

on:
  push:
    branches:
      - main

jobs:
  view-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: View contents of hello.txt
        run: |
            echo "Contents of hello.txt:"
            echo "---------------------"
            echo ""
            cat hello.txt
            echo ""
            echo "---------------------"
            echo "End of hello.txt"
